### ISSUE TITLE
Consider this argument naming structure

### ISSUE THREAD

**Issue by boshek** [bcgov/fasstr#17]
Using `add_cumulative_volume` as an example:

Right now this is the API:
```
add_cumulative_volume(data = "08NM116) ## for WSC data
add_cumulative_volume(data = *path to file*) ## user supplied data
```
I would advocate switching this to:
```
add_cumulative_volume(station_number = "08NM116) ## for WSC data
add_cumulative_volume(data = *path to file*) ## user supplied data
```
Internally the default for the WSC situation would be `tidyhydat::hy_dir()` which would then be passed to `tidyhydat::hy_daily_flows()`. That way if for some reason someone wanted to store HYDAT somewhere other than the default they could. 

Similarly for user supplied data, there is no opportunity to confuse station number in a network with their .csv or excel file that they are using for analysis.

**Comment by ateucher** [comment]
I agree with Sam on this one. It's usually good practice for a function to have consistent inputs (and outputs). Is `path to file` actually a path to a file or is the name of an object (`data.frame`) that the user already has in their environment? Looking in the code it looks like the latter.

I would actually go one step further and make a thin wrapper for wsc data around `add_cumulative_volume`:

```r
add_cumulative_volume_wsc <- function(station, ...) {
   if (!is.character(station)) {
    stop("station must be a character vector containing station numbers")
  }

   flow_data <- tidyhydat::hy_daily_flows(station_number = station)

   add_cumulative_volume(data = flow_data, ...)
}
```

Then strip out the stuff that is currently at the top of `add_cumulative_volume`

**Comment by jongoetz** [comment]
Thanks Sam and Andy,
I have added a station_number argument in addition to the data argument to separate the different data sources. I have checks to make sure at least one of them is used, and not both of them being used.  Thanks for the suggestion - I will implement the suggestion going forward in reviewing my functions.
