### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ChunChaoKuo** [bcgov/fasstr#53]
Hello Jon,

I was installing the fasstr in one of the server. 
After typing:
devtools::install_github("bcgov/fasstr", build_vignettes = TRUE)
I got the following messages:
Installation failed: schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.

Do you have any idea about how to solve the installation issue?

Thank you very much.

Regards,

**Comment by jongoetz** [comment]
I am not sure as to a solution for this issue (may be security issues and the server), but as I was able to share a tar.gz and it installed on the server no problem, I will close the Issue for now.
