### ISSUE TITLE
Version of R

### ISSUE THREAD

**Issue by pchanel** [bcgov/fasstr#64]
What version of R works with fasstrr? I keep getting the following when I try to download:
Warning in install.packages :
  package ‘fasstr’ is not available (for R version 3.6.0)

**Comment by boshek** [comment]
`fasstr` is not available on CRAN. You can install it via these instructions:

https://github.com/bcgov/fasstr#installation

**Comment by pchanel** [comment]
When I try to install fasstr I get the following message: Skipping install of 'fasstr' from a github remote, the SHA1 (ba7950c2) has not changed since last install.
  Use `force = TRUE` to force installation

Any idea why I get this?

________________________________

**Comment by boshek** [comment]
> Skipping install of 'fasstr' from a github remote, the SHA1 (ba7950c) has not changed since last install.

It means that since `fasstr` hasn't changed since you last installed it, you don't need to re-install it. If you really want to do that, use the `force = TRUE` argument. 

Have a look here for how the `remotes::install_github()` function works.
