### ISSUE TITLE
US Customary Units

### ISSUE THREAD

**Issue by shalamu** [bcgov/fasstr#77]
Thank you for writing this nice package. I am wondering how to change standard units to US customary units, eg. CFS for flow rate, and acre-ft for volumes. 
Appreciate it!

**Comment by jongoetz** [comment]
Apologies for the delay. As you noted, currently all the unit conversions for basin area, volume, and runoff are in commonly used metric units, so when using plotting functions it can be difficult to use US units as the results are converted from cubic metres per second (cms). While adding a few steps to use the area/volume-based `calc_` functions, you could convert your cfs into cms for the functions, and then back convert the resulting volume/area to US units. While it could be possible, at this time, there is no plan to include area/volume US unit conversions within functions.

However, when calculating or plotting statistics based solely on the provided streamflow units (ie. cfs) and the exported results are in the same streamflow units you do not need to convert. For example, you could provide a daily data in cfs and most basic summary stats will calculate daily, annual, monthly cfs statistics. You could even use daily cfs and use any plotting functions with the same cfs units on the y-axis (any plot with 'Discharge (cms)' axes), and then use ggplot2 functions to modify the plot and add a different axis label. See some examples below using the USGS dataRetrieval package.

Hopefully this helps.

`
library(dataRetrieval)
library(fasstr)
library(ggplot2)

#### Obtain USGS flow data
data_cfs <- dataRetrieval::readNWISdv(siteNumbers = "01491000", parameterCd = "00060")

#### Calculate stats in cfs
calc_annual_stats(data = data_cfs, values = "X_00060_00003")

#### Plot flow data in cfs (adding appropriate axis label)
plot_daily_stats(data = data_cfs, values = "X_00060_00003", end_year = 2020)[[1]]+
  ylab("Discharge, cubic feet per second")

#### Calculate low-flow frequencies in cfs, and plot probabilities and get the log PIII quantiles
low_freq <- compute_annual_frequencies(data = data_cfs, values = "X_00060_00003")
low_freq[[3]]+
  ylab("Discharge, cubic feet per second")
low_freq[5]
`

**Comment by jongoetz** [comment]
Have added vignette that will be available on the GitHub Page when the next version of fasstr is pushed to CRAN.
https://github.com/bcgov/fasstr/blob/master/vignettes/articles/fasstr_dataRetrieval.Rmd

**Comment by jongoetz** [comment]
Vignette now live on  GithubPage: https://bcgov.github.io/fasstr/articles/fasstr_dataRetrieval.html
