### ISSUE TITLE
Unable to open Hydat.sqlite3 downloaded by tidyhydat

### ISSUE THREAD

**Issue by stephenhillier** [bcgov/fasstr#80]
Hi there, I was going through the getting started example and ran into an error. It looks like  `tidyhydat::download_hydat()` downloads `Hydat.sqlite3` but fasstr checks for `HYDAT.sqlite3`:
https://github.com/bcgov/fasstr/blob/bed0d999c88e10acda48a35c9cc6edca5d00c655/R/utils.R#L30

Is that a bug or did I do something wrong (new R user here)? I was able to get around the error by creating a file named `HYDAT.sqlite3` to pass the check.

**Comment by boshek** [comment]
I can see it. @jongoetz I think you can remove that line entirely. tidyhydat will handle a missing hydat appropriately.

**Comment by jongoetz** [comment]
Welcome to the world of R, @stephenhillier! Thanks for pointing this out. 

@boshek tidyhydat does handle it. I've removed the check (https://github.com/bcgov/fasstr/commit/fbaca98a451ea3f8070f3d10a23b1ed4e14888f6) and the name of the HYDAT file should not 🤞 matter anymore. Thanks!
