### ISSUE TITLE
compute_hydate_peak_frequency() can't find Hydate.sqlite3

### ISSUE THREAD

**Issue by steffilazerte** [bcgov/fasstr#85]
On my system, the HYDAT file is `Hydat.sqlite3`. This creates problems when running `compute_hydat_peak_frequencies()` which [looks for `HYDAT.sqlite3`](https://github.com/bcgov/fasstr/blob/main/R/compute_hydat_peak_frequencies.R#L115-L117).

A possible solution would be to not check at at, and rely on `tidyhydat` functions to do the checking ([for example](https://github.com/bcgov/fasstr/blob/main/R/compute_hydat_peak_frequencies.R#L120-121), which is how it's handled in `fill_missing_dates()` via [`flowdata_import()`](https://github.com/bcgov/fasstr/blob/main/R/utils.R#L32-L33))

**Comment by boshek** [comment]
I think this just might be a typo. I think that this would be a better check:

`file.exists(tidyhydat::hy_default_db())`

**Comment by steffilazerte** [comment]
Yes, even better, I didn't see that function (in my very quick scan of tidyhydat functions!)

**Comment by jongoetz** [comment]
I removed the check for HYDAT, leaving that with tidyhydat as with the rest of the package. See https://github.com/bcgov/fasstr/commit/de240fc4e3cd96087a4742119876f2861bd5c07f
