### ISSUE TITLE
Error in names(plots)

### ISSUE THREAD

**Issue by jdalcaraz** [bcgov/fasstr#87]
Hello
Thank you for making this wonderful package. I am using it to characterize a gauging station. If I calculate the daily analysis functions (5) individually I have no problem, but when I use the function write_full_analysis() I get the following error: 
```
> write_full_analysis(data=Salas,  
+                     dates = Date,
+                     values = Value,
+                     groups = STATION_NUMBER,
+                     analyses = 1:5,
+                     water_year_start = 10,
+                     start_year=2013,
+                     months = 1:12,
+                     ignore_missing = TRUE,
+                     zyp_method = "zhang",
+                     zyp_alpha = 0.05,
+                     file_name = "Salas_Analisis")
* this may take a few moments...
** creating data frames and plots
Error in names(plots) <- paste0(daily_plots$STATION_NUMBER, ifelse(use_yield,  : 
  'names' attribute [1] must be the same length as the vector [0]
In addition: There were 33 warnings (use warnings() to see them)
```

And I can't find the solution to this problem ...

**Comment by jongoetz** [comment]
Apologies if this problem wasn't resolved, sorry for the delay. I attempted to replicate the this issue to no success. I will close the issue, but is this is still happening, I'd be happy to reopen the issue. Thanks!
