### ISSUE TITLE
fasstr::add_seasons left_join Error

### ISSUE THREAD

**Issue by dzaugis** [bcgov/fasstr#94]
Hi, 

Thanks for writing this package!

I receive an error with any function that calls `fasstr::add_seasons` and the error looks to be related to `dplyr::left_join` specifically the inclusion of the `all=TRUE` argument. I'm not sure if there is a versioning issue going on here with the version of dplyr I am using (1.1.0) and I need to revert to an older version.

Thanks

![image](https://user-images.githubusercontent.com/49949423/224102568-f8f19ac4-e46b-486a-b168-3961eab6ebbf.png)

**Comment by jongoetz** [comment]
Hi @dzaugis! Thanks for the heads up. I finally was able to have a look at the bug and it should be now fixed on the github main version. Feel free to install from github while I get the package prepped to push to CRAN.
